### ISSUE TITLE
Cannot Resolve symbol DaggerSharedPrerenceComponent and DaggerNetComponent

### ISSUE THREAD

**Issue by Anandsoni14** [vsay01/Android-Model-View-Presenter#1]
I have just cloned the project and this two errors are coming. 
DaggerSharedPrerenceComponent  :: presenters > EventsPresenter > LineNo. 37
DaggerNetComponent :: utils > MyApplication > DaggerNetComponent > Line No. 23

**Comment by vsay01** [comment]
The Component files, DaggerSharedPreferenceComponent and DaggerNetComponent, are generated after compilation. After clean and rebuild the project, it should show up.
